version: "3.9"

services:
  kali:
    image: bloatedkali3
    container_name: kali3
    privileged: true
    ports:
      - "3022:3022"  # SSH from host -> Kali
    networks:
      innet:
        ipv4_address: 172.20.0.2

  cowrie:
    image: cowrie/cowrie
    container_name: cow
    privileged: true
    networks:
      innet:
        ipv4_address: 172.20.0.3

networks:
  innet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

