from Reconfigurator.criterias.basic import BasicReconfigCriterion
from Reconfigurator.criterias.entropy import EntropyReconfigCriterion
from Reconfigurator.criterias.never import NeverReconfigCriterion
from Reconfigurator.criterias.ttest import TTestReconfigCriterion